NurseNetwork/appointments/forms.py
#!/usr/bin/python3
"""
Appointment forms
"""
from flask_wtf import FlaskForm
from wtforms import SubmitField, validators
from wtforms.validators import DataRequired
from wtforms.fields import DateField


class AppointmentForm(FlaskForm):
    appointment_date = DateField('Appointment Date', format='%Y-%m-%d',
                                 validators=[DataRequired()])
    submit = SubmitField('Book Appointment')

NurseNetwork/services/forms.py
#!/usr/bin/python3
"""
Service forms
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class ServiceForm(FlaskForm):
    """Service form"""
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description')
    price = StringField('Price', validators=[DataRequired()])
    submit = SubmitField('Create service')

NurseNetwork/appointments/routes.py
#!/usr/bin/python3
"""
Appointment routes
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import current_user, login_required
from NurseNetwork import db
from NurseNetwork.models import Service, Appointment, Patient, User, Nurse
from NurseNetwork.appointments.forms import AppointmentForm


appointments = Blueprint('appointments', __name__)


@appointments.route("/service/<id>/book_appointment", methods=['GET', 'POST'],
                    strict_slashes=False)
@login_required
def book_appointment(id):
    """Books a new appointment"""
    form = AppointmentForm()
    if form.validate_on_submit():
        service = Service.query.filter_by(id=id).first()
        if current_user.user_type == 'patient':
            patient = Patient.query.filter_by(user_id=current_user.id).first()
            appointment_date = form.appointment_date.data
            new_appointment = Appointment(nurse_id=service.nurse_id,
                                        patient_id=patient.id,
                                        service_id=service.id,
                                        appointment_date=appointment_date)
            db.session.add(new_appointment)
            db.session.commit()
            flash('Appointment booked successfully', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('A nurse cannot book appointments', 'danger')
            return redirect(url_for('main.home'))
    return render_template('new_appointment.html',
                           title='New Appointment',
                           form=form)


@appointments.route('/account/<id>/appointments', methods=['GET'],
                    strict_slashes=False)
@login_required
def retrieve_appointments(id):
    """Retrieves an appointment"""
    if current_user.user_type == 'nurse':
        nurse = Nurse.query.filter_by(user_id=id).first()
        if nurse:
            appointments = nurse.appointments
            return render_template(
                'nurse_appointments.html', appointments=appointments,
                User=User, Nurse=Nurse, Patient=Patient, Service=Service
            )
        flash('Not found!')
        return render_template(url_for('main.home'))
    patient = Patient.query.filter_by(user_id=id).first()
    if patient:
        appointments = patient.appointments
        return render_template(
            'patient_appointments.html', appointments=appointments,
            User=User, Nurse=Nurse, Patient=Patient, Service=Service
        )
    flash('Not found!')
    return redirect(url_for('main.home'))

NurseNetwork/reviews/routes.py
#!/usr/bin/python3
"""
Review routes
"""
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import current_user, login_required
from NurseNetwork import db
from NurseNetwork.models import Appointment, Review, User, Nurse, Patient
from NurseNetwork.reviews.forms import ReviewForm


reviews = Blueprint('reviews', __name__)


@reviews.route("/appointments/<id>/new_review", methods=['GET', 'POST'],
               strict_slashes=False)
@login_required
def new_review(id):
    """Creates a new review"""
    form = ReviewForm()
    if form.validate_on_submit():
        appointment = Appointment.query.filter_by(id=id).first()
        description = form.feedback.data
        stars = int(form.stars.data)
        new_review = Review(appointment_id=appointment.id,
                            nurse_id=appointment.nurse_id,
                            description=description,
                            stars=stars)
        db.session.add(new_review)
        db.session.commit()
        flash('Review added successfully', 'success')
        return redirect(url_for('main.home'))
    return render_template('new_review.html',
                           title='New review',
                           form=form)


@reviews.route('/account/<id>/reviews', methods=['GET'],
               strict_slashes=False)
@reviews.route('/account/<id>/reviews/<review_id>', methods=['GET'],
           strict_slashes=False)
def retrieve_reviews(id, review_id=None):
    """Retrieves a review"""
    if review_id:
        review = Review.query.filter_by(id=review_id).first()
        if review:
            return render_template(
                'reviews.html', reviews=reviews, User=User,
                Nurse=Nurse, Patient=Patient, Appointment=Appointment
            )
        flash('Review not found!')
        return redirect(url_for('main.home'))
    if current_user.user_type == 'nurse':
        nurse = Nurse.query.filter_by(user_id=id).first()
        if nurse:
            reviews = nurse.reviews
            return render_template(
                'reviews.html', reviews=reviews, User=User,
                Nurse=Nurse, Patient=Patient, Appointment=Appointment
            )
        flash('Nurse not found!')
    return redirect(url_for('main.home'))


# @reviews.route('/reviews/<review_id>', methods=['DELETE'],
#            strict_slashes=False)
# def delete_review(id, review_id):
#     review = Review.query.filter_by(id=review_id).first()
#     if review:
#         db.session.delete(review)
#         db.session.commit()
#         return jsonify({"message":"Review deleted successfully!"})
#     return jsonify({"error":"Review not found!"})

NurseNetwork/services/routes.py
#!/usr/bin/python3
"""
Service routes
"""
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, jsonify
from flask_login import current_user, login_required
from NurseNetwork import db
from NurseNetwork.models import Service, User, Nurse
from NurseNetwork.services.forms import ServiceForm


services = Blueprint('services', __name__)


@services.route("/service/new", strict_slashes=False, methods=['GET', 'POST'])
@login_required
def new_service():
    """Creates a new service"""
    if current_user.user_type != 'nurse':
        abort(403)
    form = ServiceForm()
    if form.validate_on_submit():
        nurse = Nurse.query.filter_by(user_id=current_user.id).first()
        new_service = Service(title=form.title.data,
                              description=form.description.data,
                              price=form.price.data,
                              nurse_id=nurse.id)
        db.session.add(new_service)
        db.session.commit()
        flash('Your service has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_service.html', title='New Service', form=form)


@services.route("/service/<id>", strict_slashes=False,
           methods=['GET'])
def service(id):
    """Retrieves a service"""
    service = Service.query.get_or_404(id)
    return render_template('service.html', title=service.title,
                           service=service, Nurse=Nurse, User=User)


@services.route("/service/<id>/update", strict_slashes=False,
           methods=['Get', 'POST'])
@login_required
def update_service(id):
    """Updates a service"""
    service = Service.query.get_or_404(id)
    nurse = Nurse.query.get_or_404(service.nurse_id)
    user = User.query.get_or_404(nurse.user_id)
    if user != current_user:
        abort(403)
    form = ServiceForm()
    if form.validate_on_submit():
        service.title = form.title.data
        service.description = form.description.data
        service.price = form.price.data
        db.session.commit()
        flash('Service updated successfully!', 'success')
        return redirect(url_for('services.service', id=service.id))
    return render_template('update_service.html', title='Update service',
                           service=service, nurse=nurse, user=user,
                           form=form)


@services.route("/service/<id>/delete", strict_slashes=False,
           methods=['POST'])
@login_required
def delete_service(id):
    """Deletes a service"""
    service = Service.query.get_or_404(id)
    nurse = Nurse.query.get_or_404(service.nurse_id)
    user = User.query.get_or_404(nurse.user_id)
    if user != current_user:
        abort(403)
    db.session.delete(service)
    db.session.commit()
    flash('Service deleted successfully', 'success')
    return redirect(url_for('main.home'))


@services.route('/nurses/<id>/services/', methods=['GET'], strict_slashes=False)
@services.route('/nurses/<id>/services/<service_id>', methods=['GET'],
           strict_slashes=False)
def retrieve_nurse_services(id, service_id=None):
    """Retrieves services assigned to a particular nurse"""
    if service_id:
        service = Service.query.filter_by(id=service_id).first()
        if service:
            return render_template('nurse_service.html', services=service,
                                   Nurse=Nurse, User=User)
        abort(404)
    nurse = Nurse.query.filter_by(user_id=id).first()
    services = nurse.services
    if len(services) > 0:
        services_tojson = []
        for i in range(0, len(services)):
            services_tojson.append(services[i].to_dict())
        return render_template('nurse_service.html', services=services_tojson,
                               Nurse=Nurse, User=User)
    flash('No services found!')
    return redirect(url_for('main.home'))

NurseNetwork/users/routes.py
#!/usr/bin/python3
"""
Users routes
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from NurseNetwork import db, bcrypt
from NurseNetwork.models import User, Service, Nurse, Patient
from NurseNetwork.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm)
from NurseNetwork.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'],
        strict_slashes=False)
def register():
    """Registers a new user"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(username=form.username.data, email=form.email.data,
                        password=hashed_pwd, user_type=form.user_type.data)
        db.session.add(new_user)
        db.session.commit()

        if new_user.user_type == 'nurse':
            new_nurse = Nurse(user_id=new_user.id)
            db.session.add(new_nurse)
        else:
            new_patient = Patient(user_id=new_user.id)
            db.session.add(new_patient)
        db.session.commit()

        flash('Your account has been created! Please log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'],
        strict_slashes=False)
def login():
    """Logs the user in"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('You have been logged in!', 'success')
            next_page = request.args.get('next')
            return redirect(url_for(next_page.strip('/') if next_page else 'main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout", strict_slashes=False)
def logout():
    """Logs the user out"""
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/reset_password", strict_slashes=False,
           methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password',
                           form=form)


@users.route("/reset_password/<token>", strict_slashes=False,
           methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pwd
        db.session.commit()

        flash('Your password has been updated! Please log in', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_token.html', title='Reset Password',
                           form=form)

    return redirect(url_for('main.home'))


@users.route("/account", strict_slashes=False,
        methods=['GET', 'POST'])
@login_required
def account(id=None):
    """The user's account page"""
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.profile_pic.data:
            picture_file = save_picture(form.profile_pic.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/profile/<user_id>", strict_slashes=False,
        methods=['GET'])
def profile(user_id):
    """The user's profile page"""
    user = User.query.get_or_404(user_id)
    nurse = Nurse.query.filter_by(user_id=user_id).first()
    image_file = url_for('static', filename=user.image_file)
    return render_template('profile.html', title='Profile',
                           user=user, nurse=nurse,
                           image_file=image_file)


@users.route('/users', methods=['GET'], strict_slashes=False)
@users.route('/users/<id>', methods=['GET'], strict_slashes=False)
def retrieve_users(id=None):
    """Retrieves a user by its id if available, else all users"""
    if id:
        user = User.query.filter_by(id=id).first()
        if user:
            return jsonify(user.to_dict())
        abort(404)
    else:
        users = User.query.all()
        users_tojson = []
        for i in range(0, len(users)):
            users_tojson.append(users[i].to_dict())
        return jsonify(users_tojson)

NurseNetwork/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="mt-4 mb-3">About Page</h1>
{% endblock %}

NurseNetwork/templates/appointment.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Appontment</legend>
                <div class="form-group">
                    {{ form.appointment_date.label(class="form-control-label") }}
                    {% if form.appointment_date.errors %}
                        {{ form.appointment_date(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.appointment_date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.appointment_date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

NurseNetwork/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-brand") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

NurseNetwork/templates/new_appointment.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Appontment</legend>
                <div class="form-group">
                    {{ form.appointment_date.label(class="form-control-label") }}
                    {% if form.appointment_date.errors %}
                        {{ form.appointment_date(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.appointment_date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.appointment_date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-brand") }}
            </div>
        </form>
    </div>
{% endblock content %}

NurseNetwork/templates/nurse_appointments.html
{% extends 'layout.html' %}
{% block content %}
    {% for appointment in appointments %}
        {% set nurse = Nurse.query.filter_by(id=appointment.nurse_id).first() %}
        {% set patient = Patient.query.filter_by(id=appointment.patient_id).first() %}
        {% set user = User.query.filter_by(id=nurse.user_id).first() %}
        {% set service = Service.query.filter_by(id=appointment.service_id).first() %}
        <article class="media content-section mt-4">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename=user.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.profile', user_id=user.id) }}">{{ user.username }}</a>
                    <small class="text-muted">{{ appointment.to_dict()['created_at']}}</small>
                </div>
                <h4><a class="article-title" href="{{ url_for('appointments.retrieve_appointments', id=user.id) }}">Patient: {{ User.query.filter_by(id=patient.user_id).first().to_dict()['username'] }}</a></h2>
                <p class="article-content">Date: {{ appointment.to_dict()['appointment_date'] }}</p>
                <p class="article-content">Service: <a href="{{ url_for('services.service', id=service.id) }}">{{ service.to_dict()['title'] }}</a></p>
            </div>
        </article>
    {% endfor %}
{% endblock %}

NurseNetwork/templates/profile.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
                <p class="text-secondary">{{ user.user_type }}</p>
                <p class="text-secondary">Joined on {{ user.created_at }}</p>
            </div>
        </div>
    </div>
    <div class="content-section">
    </div>
{% endblock %}

{% block sidebar %}
    <div class="content-section">
        <h3>Still Curious?</h3>
        <p class='text-muted'>Discover Further</p>
        <div class="row">
            <div class="col mb-2">
                <a href="{{ url_for('services.retrieve_nurse_services', id=nurse.id) }}" class="btn btn-brand btn-block">Services</a>
            </div>
        </div>
        <div class="row">
            <div class="col mb-2">
                <a href="{{ url_for('reviews.retrieve_reviews', id=nurse.user_id) }}" class="btn btn-brand btn-block">Reviews</a>
            </div>
        </div>
        <div class="row">
            <div class="col mb-2">
                <a href="" class="btn btn-brand btn-block">Ask {{ user.username }}</a>
            </div>
        </div>
        <!-- <div class="row"> -->
        <!--     <div class="col mb-2"> -->
        <!--         <a href="#" class="btn btn-brand btn-block">Book an Appointment</a> -->
        <!--     </div> -->
        <!-- </div> -->
    </div>
{% endblock %}

NurseNetwork/templates/rev.html
<!-- {% extends 'layout.html' %} -->
<!-- {% block content %} -->
<!--     {% for review in reviews %} -->
<!--         {% set nurse = Nurse.query.filter_by(id=review.nurse_id).first() %} -->
<!--         {% set user = User.query.filter_by(id=nurse.user_id).first() %} -->
<!--         <!-- {% set appointment = Appointment.query.filter_by(id=review.appointment_id).first() %} --> -->
<!--         {% set patient = Patient.query.filter_by(id=appointment.patient_id).first() %} -->
<!--         {% set service = Service.query.filter_by(id=appointment.service_id).first() %} -->
<!--         <article class="media content-section mt-4"> -->
<!--             <img class="rounded-circle article-img" src="{{ url_for('static', filename=user.image_file) }}"> -->
<!--             <div class="media-body"> -->
<!--                 <div class="article-metadata"> -->
<!--                     <a class="mr-2" href="{{ url_for('users.profile', user_id=user.id) }}">{{ user.username }}</a> -->
<!--                     <small class="text-muted">{{ review.to_dict()['created_at']}}</small> -->
<!--                 </div> -->
<!--                 <h4><a class="article-title" href="{{ url_for('reviews.retrieve_reviews', id=user.id) }}">Patient: {{ patient.to_dict()['username'] }}</a></h2> -->
<!--                 <p class="article-content">Feedback: {{ review.to_dict()['description'] }}</p> -->
<!--                 <p class="article-content">Service: <a href="{{ url_for('services.service', id=service.id) }}">{{ service.to_dict()['title'] }}</a></p> -->
<!--             </div> -->
<!--         </article> -->
<!--     {% endfor %} -->
<!-- {% endblock %} -->

NurseNetwork/templates/reviews.html
{% extends 'layout.html' %}
{% block content %}
    {% if reviews is iterable %}
        {% for review in reviews %}
            {% set appointment = Appointment.query.filter_by(id=review.appointment_id).first() %}
            {% set patient = Patient.query.filter_by(id=appointment.patient_id).first() %}
            {% set user = User.query.filter_by(id=patient.user_id).first() %}
            <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename=user.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{{ url_for('users.profile', user_id=user.id) }}">{{ user.username }}</a>
                        <small class="text-muted">{{ review['created_at']}}</small>
                    </div>
                    <p class="article-content">{{ review['description'] }}</p>
                    <p class="article-content">Stars: {{ review['stars'] }}</p>
                </div>
            </article>
        {% endfor %}
    {% else %}
        {% set appointment = Appointment.query.filter_by(id=review.appointment_id).first() %}
        {% set patient = Patient.query.filter_by(id=appointment.patient_id).first() %}
        {% set user = User.query.filter_by(id=patient.user_id).first() %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename=user.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.profile', user_id=user.id) }}">{{ user.username }}</a>
                    <small class="text-muted">{{ reviews.to_dict()['created_at']}}</small>
                </div>
                <p class="article-content">{{ reviews.to_dict()['description'] }}</p>
                <p class="article-content">Stars: {{ reviews.to_dict()['stars'] }}</p>
            </div>
        </article>
    {% endif %}
{% endblock %}

NurseNetwork/templates/service.html
{% extends 'layout.html' %}
{% block content %}
    {% set nurse = Nurse.query.filter_by(id=service.nurse_id).first() %}
    {% set user = User.query.filter_by(id=nurse.user_id).first() %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename=user.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.profile', user_id=user.id) }}">{{ user.username }}</a>
                <small class="text-muted">{{ service.to_dict()['created_at']}}</small>
                {% if user == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('services.update_service', id=service.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ service.to_dict()['title'] }}</h2>
            <p class="article-content">{{ service.to_dict()['description'] }}</p>
            <p class="article-content">Price: {{ service.to_dict()['price'] }}$</p>
            <div>
                {% if current_user != user %}
                <a href="{{ url_for('appointments.book_appointment', id=service.id) }}" class="btn btn-brand">Book an appointment</a>
                    <a href="#" class="btn btn-secondary">Ask {{ user.username }}</a>
                {% endif %}
            </div>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Service?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('services.delete_service', id=service.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}